// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AccountCreateRequest struct {
	Name     string       `json:"name" validate:"required"`
	Password string       `json:"password" validate:"required"`
	Email    string       `json:"email" validate:"required"`
	Status   bool         `json:"status,optional"`
	Roles    []*IDRequest `json:"roles,optional"`
}

type AccountInfo struct {
	ID     int64              `json:"id"`
	Name   string             `json:"name"`
	Email  string             `json:"email"`
	Status bool               `json:"status"`
	Roles  []*AccountRoleInfo `json:"roles"`
}

type AccountListRequest struct {
	PageRequest
	ID int64 `json:"id,optional"`
}

type AccountListResponse struct {
	PageResponse
	Data []*AccountInfo `json:"data"`
}

type AccountRoleInfo struct {
	ID   int64  `json:"id"`
	Name string `json:"name,omitempty"`
}

type AccountUpdateRequest struct {
	ID       int64        `json:"id" validate:"required"`
	Name     *string      `json:"name,optional"`
	Password *string      `json:"password,optional"`
	Email    *string      `json:"email,optional"`
	Status   *bool        `json:"status,optional"`
	Roles    []*IDRequest `json:"roles,optional"`
}

type IDRequest struct {
	ID int64 `path:"id" form:"id" json:"id"`
}

type IDResponse struct {
	ID int64 `json:"id"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResponse struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int64  `json:"expires_in"`
}

type MenuAllInfo struct {
	ID        int64  `json:"id"`
	Pid       int64  `json:"pid"`
	MenuType  int    `json:"menu_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort"`
	ApiUrl    string `json:"api_url"`
	ApiMethod string `json:"api_method"`
	Visible   bool   `json:"visible"`
	Status    bool   `json:"status"`
}

type MenuCreateRequest struct {
	Name      string `json:"name" validate:"required"`
	MenuType  int    `json:"menu_type" validate:"required"`
	Path      string `json:"path" validate:"required"`
	Component string `json:"component"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort,optional"`
	ApiUrl    string `json:"api_url"`
	ApiMethod string `json:"api_method"`
	Visible   bool   `json:"visible,optional"`
	Status    bool   `json:"status,optional"`
	Pid       int64  `json:"pid"`
	Remark    string `json:"remark"`
}

type MenuInfo struct {
	ID        int64  `json:"id"`
	Pid       int64  `json:"pid"`
	MenuType  int    `json:"menu_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort"`
	ApiUrl    string `json:"api_url"`
	ApiMethod string `json:"api_method"`
	Visible   bool   `json:"visible"`
	Status    bool   `json:"status"`
	Remark    string `json:"remark"`
}

type MenuListRequest struct {
	PageRequest
	ID     int64  `json:"id,optional"`
	Name   string `json:"name,optional"`
	Status bool   `json:"status,optional"`
}

type MenuListResponse struct {
	PageResponse
	Data []*MenuInfo `json:"data"`
}

type MenuUpdateRequest struct {
	ID        int64   `json:"id" validate:"required"`
	Name      *string `json:"name,optional"`
	MenuType  *int    `json:"menu_type,optional"`
	Path      *string `json:"path,optional"`
	Component *string `json:"component,optional"`
	Icon      *string `json:"icon,optional"`
	Sort      *int    `json:"sort,optional"`
	ApiUrl    *string `json:"api_url,optional"`
	ApiMethod *string `json:"api_method,optional"`
	Visible   *bool   `json:"visible,optional"`
	Status    *bool   `json:"status,optional"`
	Pid       *int64  `json:"pid,optional"`
	Remark    *string `json:"remark,optional"`
}

type PageRequest struct {
	Page int64 `path:"page" form:"page" json:"page"`
	Size int64 `path:"size" form:"size" json:"size"`
}

type PageResponse struct {
	Total int64 `json:"total"`
	Page  int64 `json:"page"`
	Size  int64 `json:"size"`
}

type ProfileMenuInfo struct {
	ID        int64  `json:"id"`
	Pid       int64  `json:"pid"`
	MenuType  int    `json:"menu_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort"`
	ApiUrl    string `json:"api_url"`
	ApiMethod string `json:"api_method"`
	Visible   bool   `json:"visible"`
	Status    bool   `json:"status"`
	Remark    string `json:"remark"`
}

type ProfileResponse struct {
	ID    int64              `json:"id"`
	Name  string             `json:"name"`
	Email string             `json:"email"`
	Roles []*ProfileRoleInfo `json:"roles"`
	Menus []*ProfileMenuInfo `json:"menus"`
}

type ProfileRoleInfo struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterRequest struct {
	Name     string `json:"name" validate:"required"`
	Email    string `json:"email" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type RegisterResponse struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type RoleAllInfo struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Sort   int    `json:"sort"`
	Status bool   `json:"status"`
	Remark string `json:"remark"`
}

type RoleAssociateMenusRequest struct {
	ID      int64   `json:"id" validate:"required"`
	MenuIds []int64 `json:"menu_ids" validate:"required"`
}

type RoleCreateRequest struct {
	Name   string       `json:"name" validate:"required"`
	Sort   int          `json:"sort,optional"`
	Status bool         `json:"status,optional"`
	Remark string       `json:"remark"`
	Menus  []*IDRequest `json:"menus,optional"`
}

type RoleInfo struct {
	ID     int64           `json:"id"`
	Name   string          `json:"name"`
	Sort   int             `json:"sort"`
	Status bool            `json:"status"`
	Remark string          `json:"remark"`
	Menus  []*RoleMenuInfo `json:"menus"`
}

type RoleListRequest struct {
	PageRequest
	ID int64 `json:"id,optional"`
}

type RoleListResponse struct {
	PageResponse
	Data []*RoleInfo `json:"data"`
}

type RoleMenuInfo struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RoleUpdateRequest struct {
	ID     int64        `json:"id" validate:"required"`
	Name   *string      `json:"name,optional"`
	Sort   *int         `json:"sort,optional"`
	Status *bool        `json:"status,optional"`
	Remark *string      `json:"remark,optional"`
	Menus  []*IDRequest `json:"menus,optional"`
}
